#!/usr/bin/env bash
# SOVEREIGN Platform — Context Gather Script — Session 44
# GD-23: ProgramStatusSurface (docs/20)
# Generated by Governance Agent, July 19, 2026, from a verified clone of origin/main.
# Run from the monorepo root: ~/Developer/sovereign-platform/
#
# NOTE: verify these paths still match before relying on this blindly if significant
# time has passed since July 19 — `git pull` first (Rule 1).

set -euo pipefail

FILES=(
  # Governance context — the spec itself is the design authority
  "docs/20_Cross_Module_Data_Surface_Architecture.md"
  "AGENT_REFERENCE.md"

  # D1 — shell-contract + the exact template to copy
  "shell-contract.ts"
  "sovereign-shell/shell-contract.ts"
  "sovereign-shell/src/shell.ts"

  # D2 — APEX's existing structured data
  "module-apex/src/PPBEDashboard.tsx"
  "module-apex/src/apex-contract.ts"

  # D3 — VIGIL's integration point
  "module-vigil/src/approval-engine.ts"
)

OUTPUT=""
FOUND=0
MISSING_LIST=()

for f in "${FILES[@]}"; do
  if [[ -f "$f" ]]; then
    OUTPUT+=$'\n\n# ============================================================\n'
    OUTPUT+="# FILE: $f"
    OUTPUT+=$'\n# ============================================================\n\n'
    OUTPUT+="$(cat "$f")"
    FOUND=$((FOUND+1))
  else
    MISSING_LIST+=("$f")
  fi
done

echo "$OUTPUT" | pbcopy

MISSING=${#MISSING_LIST[@]}
echo "Session 44 gather complete: $FOUND of ${#FILES[@]} files found, $MISSING missing."
if [[ $MISSING -gt 0 ]]; then
  echo "Missing files — check these paths before proceeding:"
  for m in "${MISSING_LIST[@]}"; do
    echo "  - $m"
  done
fi
echo "Context copied to clipboard."
