#!/usr/bin/env bash
# SOVEREIGN Platform — Context Gather Script — Session 39
# Walkthrough F Repeat Pass — Findings Remediation
# Generated by Governance Agent, July 18, 2026, from a verified clone of origin/main.
# Run from the monorepo root: ~/Developer/sovereign-platform/
#
# NOTE: verify these paths still match before relying on this blindly if significant
# time has passed since July 18 — `git pull` first (Rule 1).

set -euo pipefail

FILES=(
  # Governance context
  "AGENT_REFERENCE.md"
  "Agent_Identity_Standard.md"
  "SOVEREIGN_Platform_Integration_Brief_v1.47.md"
  "docs/18_PPBE_Workflow_Architecture.md"

  # VIGIL — approval brief + gate (D1, D2)
  "module-vigil/src/approval-engine.ts"
  "module-vigil/src/approval-contract.ts"
  "module-vigil/src/useApprovalBrief.ts"
  "module-vigil/src/useApprovalDecision.ts"
  "module-vigil/src/useApprovalQueue.ts"
  "module-vigil/src/ApprovalDecisionPanel.tsx"
  "module-vigil/src/ApprovalDetail.tsx"
  "module-vigil/src/ApprovalQueue.tsx"
  "module-vigil/src/AgentApprovalQueue.tsx"

  # SCRIBE — exhibit drafter (D1)
  "module-scribe/src/ppbe-exhibit-engine.ts"
  "module-scribe/src/ppbe-exhibit-contract.ts"
  "module-scribe/src/PPBEExhibitPanel.tsx"

  # NEXUS — coordination panel (D1 plain-language pass, D3/D4 button affordance + line wrap)
  "module-nexus/src/PPBECoordinationPanel.tsx"
)

OUTPUT=""
FOUND=0
MISSING_LIST=()

for f in "${FILES[@]}"; do
  if [[ -f "$f" ]]; then
    OUTPUT+=$'\n\n# ============================================================\n'
    OUTPUT+="# FILE: $f"
    OUTPUT+=$'\n# ============================================================\n\n'
    OUTPUT+="$(cat "$f")"
    FOUND=$((FOUND+1))
  else
    MISSING_LIST+=("$f")
  fi
done

echo "$OUTPUT" | pbcopy

MISSING=${#MISSING_LIST[@]}
echo "Session 39 gather complete: $FOUND of ${#FILES[@]} files found, $MISSING missing."
if [[ $MISSING -gt 0 ]]; then
  echo "Missing files — check these paths before proceeding:"
  for m in "${MISSING_LIST[@]}"; do
    echo "  - $m"
  done
fi
echo "Context copied to clipboard."
