#!/usr/bin/env bash
# SOVEREIGN Platform — Context Gather Script — Session 42
# Module labels/hover info + VIGIL card polish (WF-25 - WF-28)
# Generated by Governance Agent, July 19, 2026, from a verified clone of origin/main.
# Run from the monorepo root: ~/Developer/sovereign-platform/
#
# NOTE: verify these paths still match before relying on this blindly if significant
# time has passed since July 19 — `git pull` first (Rule 1).

set -euo pipefail

FILES=(
  # Governance context
  "AGENT_REFERENCE.md"
  "SOVEREIGN_Session41_Handoff.md"

  # D1 — sidebar labels + hover info
  "sovereign-shell/src/navigation/ModuleNav.tsx"
  "sovereign-shell/src/navigation/theme.ts"

  # D2 + D3 — VIGIL card + detail
  "module-vigil/src/ApprovalQueue.tsx"
  "module-vigil/src/ApprovalDetail.tsx"
  "module-vigil/src/approval-engine.ts"
  "module-vigil/src/vigil-types.ts"

  # D4 — LENS source document
  "module-lens/src/source-documents.ts"
)

OUTPUT=""
FOUND=0
MISSING_LIST=()

for f in "${FILES[@]}"; do
  if [[ -f "$f" ]]; then
    OUTPUT+=$'\n\n# ============================================================\n'
    OUTPUT+="# FILE: $f"
    OUTPUT+=$'\n# ============================================================\n\n'
    OUTPUT+="$(cat "$f")"
    FOUND=$((FOUND+1))
  else
    MISSING_LIST+=("$f")
  fi
done

echo "$OUTPUT" | pbcopy

MISSING=${#MISSING_LIST[@]}
echo "Session 42 gather complete: $FOUND of ${#FILES[@]} files found, $MISSING missing."
if [[ $MISSING -gt 0 ]]; then
  echo "Missing files — check these paths before proceeding:"
  for m in "${MISSING_LIST[@]}"; do
    echo "  - $m"
  done
fi
echo "Context copied to clipboard."
