#!/usr/bin/env bash
# SOVEREIGN Platform — Context Gather Script — Session 46
# APEX Execution Monitoring — charts, selection, drill-through, site placeholder
# Generated by Governance Agent, July 20, 2026, from a verified clone of origin/main.
# Run from the monorepo root: ~/Developer/sovereign-platform/
#
# NOTE: verify these paths still match before relying on this blindly if significant
# time has passed since July 20 — `git pull` first (Rule 1).

set -euo pipefail

FILES=(
  # D1 — the data + threshold logic to reuse
  "module-apex/src/ppbe-dashboard.ts"
  "module-apex/src/PPBEDashboard.tsx"
  "module-apex/src/apex-contract.ts"

  # D2 — the existing selection/drill-through mechanism
  "module-apex/src/ApexApp.tsx"

  # D3 — the frozen entity, so Build Agent sees exactly what NOT to touch
  "sovereign-data/src/entities/program-record.ts"
)

OUTPUT=""
FOUND=0
MISSING_LIST=()

for f in "${FILES[@]}"; do
  if [[ -f "$f" ]]; then
    OUTPUT+=$'\n\n# ============================================================\n'
    OUTPUT+="# FILE: $f"
    OUTPUT+=$'\n# ============================================================\n\n'
    OUTPUT+="$(cat "$f")"
    FOUND=$((FOUND+1))
  else
    MISSING_LIST+=("$f")
  fi
done

echo "$OUTPUT" | pbcopy

MISSING=${#MISSING_LIST[@]}
echo "Session 46 gather complete: $FOUND of ${#FILES[@]} files found, $MISSING missing."
if [[ $MISSING -gt 0 ]]; then
  echo "Missing files — check these paths before proceeding:"
  for m in "${MISSING_LIST[@]}"; do
    echo "  - $m"
  done
fi
echo "Context copied to clipboard."
