#!/usr/bin/env bash
# SOVEREIGN Platform — Context Gather Script — Session 47
# Home Dashboard Phase 1 — Program Health, Flagged Programs, Module Orientation
# Generated by Governance Agent, July 20, 2026, from a verified clone of origin/main.
# Run from the monorepo root: ~/Developer/sovereign-platform/
#
# NOTE: verify these paths still match before relying on this blindly if significant
# time has passed since July 20 — `git pull` first (Rule 1).

set -euo pipefail

FILES=(
  # Governance context
  "SOVEREIGN_Home_Dashboard_Design_20260720.md"

  # D1/D2 — the surface to read
  "shell-contract.ts"
  "sovereign-shell/src/shell.ts"

  # D1-D4 — the actual page being redesigned
  "sovereign-shell/src/PlatformHome.tsx"

  # D3 — the existing module info to reuse
  "sovereign-shell/src/navigation/ModuleNav.tsx"
)

OUTPUT=""
FOUND=0
MISSING_LIST=()

for f in "${FILES[@]}"; do
  if [[ -f "$f" ]]; then
    OUTPUT+=$'\n\n# ============================================================\n'
    OUTPUT+="# FILE: $f"
    OUTPUT+=$'\n# ============================================================\n\n'
    OUTPUT+="$(cat "$f")"
    FOUND=$((FOUND+1))
  else
    MISSING_LIST+=("$f")
  fi
done

echo "$OUTPUT" | pbcopy

MISSING=${#MISSING_LIST[@]}
echo "Session 47 gather complete: $FOUND of ${#FILES[@]} files found, $MISSING missing."
if [[ $MISSING -gt 0 ]]; then
  echo "Missing files — check these paths before proceeding:"
  for m in "${MISSING_LIST[@]}"; do
    echo "  - $m"
  done
fi
echo "Context copied to clipboard."
