#!/usr/bin/env bash
# SOVEREIGN Platform — Context Gather Script — Session 43
# Fix confirmed e2e/verification findings — WF-14, repo duplicate, stale verify script
# Generated by Governance Agent, July 19, 2026, from a verified clone of origin/main.
# Run from the monorepo root: ~/Developer/sovereign-platform/
#
# NOTE: verify these paths still match before relying on this blindly if significant
# time has passed since July 19 — `git pull` first (Rule 1).

set -euo pipefail

FILES=(
  # Governance context
  "SOVEREIGN_EndToEnd_Assessment_20260719.md"

  # D1 — the seven WF-14 locations + the test file
  "sovereign-shell/src/PlatformHome.tsx"
  "module-apex/src/PPBEAgentsPanel.tsx"
  "module-counsel/src/PreMortemStudio.tsx"
  "module-counsel/src/CounterargumentPanel.tsx"
  "module-counsel/src/DecisionFramer.tsx"
  "module-counsel/src/AnalysisPanel.tsx"
  "e2e/tests/wcag-contrast.test.ts"

  # D2 — duplicate doc
  "docs/12_NEXUS_Architecture.md"
  "12_NEXUS_Architecture.md"

  # D3 — verification script
  "sovereign_session_verify.sh"
)

OUTPUT=""
FOUND=0
MISSING_LIST=()

for f in "${FILES[@]}"; do
  if [[ -f "$f" ]]; then
    OUTPUT+=$'\n\n# ============================================================\n'
    OUTPUT+="# FILE: $f"
    OUTPUT+=$'\n# ============================================================\n\n'
    OUTPUT+="$(cat "$f")"
    FOUND=$((FOUND+1))
  else
    MISSING_LIST+=("$f")
  fi
done

echo "$OUTPUT" | pbcopy

MISSING=${#MISSING_LIST[@]}
echo "Session 43 gather complete: $FOUND of ${#FILES[@]} files found, $MISSING missing."
if [[ $MISSING -gt 0 ]]; then
  echo "Missing files — check these paths before proceeding:"
  for m in "${MISSING_LIST[@]}"; do
    echo "  - $m"
  done
fi
echo "Context copied to clipboard."
