#!/usr/bin/env bash
# SOVEREIGN Platform — Context Gather Script — Session 41
# GD-22: Role-Based Access Matrix
# Generated by Governance Agent, July 18, 2026, from a verified clone of origin/main.
# Run from the monorepo root: ~/Developer/sovereign-platform/
#
# NOTE: verify these paths still match before relying on this blindly if significant
# time has passed since July 18 — `git pull` first (Rule 1).

set -euo pipefail

FILES=(
  # Governance context
  "AGENT_REFERENCE.md"
  "SOVEREIGN_Role_Access_Matrix_20260718.md"
  "SOVEREIGN_Design_Recommendations_20260718.md"

  # D1 — shell-contract + access policy
  "shell-contract.ts"
  "sovereign-shell/shell-contract.ts"
  "sovereign-shell/src/module-loader/index.ts"
  "sovereign-shell/src/navigation/ModuleNav.tsx"

  # D2 — the nine non-ARIA modules' registration files
  "module-counsel/src/index.ts"
  "module-scribe/src/index.ts"
  "module-vigil/src/index.ts"
  "module-lens/src/index.ts"
  "module-cpmi/src/index.ts"
  "module-agentos/src/index.ts"
  "module-nexus/src/index.ts"
  "module-apex/src/index.ts"
  "module-flowpath/src/index.ts"

  # D3 — ARIA
  "module-aria/src/index.ts"
  "module-aria/src/AriaApp.tsx"

  # D4 — persona toggle
  "sovereign-shell/src/main.tsx"
)

OUTPUT=""
FOUND=0
MISSING_LIST=()

for f in "${FILES[@]}"; do
  if [[ -f "$f" ]]; then
    OUTPUT+=$'\n\n# ============================================================\n'
    OUTPUT+="# FILE: $f"
    OUTPUT+=$'\n# ============================================================\n\n'
    OUTPUT+="$(cat "$f")"
    FOUND=$((FOUND+1))
  else
    MISSING_LIST+=("$f")
  fi
done

echo "$OUTPUT" | pbcopy

MISSING=${#MISSING_LIST[@]}
echo "Session 41 gather complete: $FOUND of ${#FILES[@]} files found, $MISSING missing."
if [[ $MISSING -gt 0 ]]; then
  echo "Missing files — check these paths before proceeding:"
  for m in "${MISSING_LIST[@]}"; do
    echo "  - $m"
  done
fi
echo "Context copied to clipboard."
