#!/usr/bin/env bash
# SOVEREIGN Platform — Context Gather Script — Session 40
# Quick Build — DR-1 (Tier 1), DR-2, DR-3 (near-term move)
# Generated by Governance Agent, July 18, 2026, from a verified clone of origin/main.
# Run from the monorepo root: ~/Developer/sovereign-platform/
#
# NOTE: verify these paths still match before relying on this blindly if significant
# time has passed since July 18 — `git pull` first (Rule 1).

set -euo pipefail

FILES=(
  # Governance context
  "AGENT_REFERENCE.md"
  "SOVEREIGN_Design_Recommendations_20260718.md"

  # D2 — persona toggle
  "sovereign-shell/src/main.tsx"
  "shell-contract.ts"

  # D1 — Outlook honest-placeholder buttons
  "module-scribe/src/TTManagerReview.tsx"

  # D3 — VIGIL obligation brief + APEX data adapter (investigate-first)
  "module-vigil/src/approval-engine.ts"
  "module-apex/src/apex-data-adapter.ts"
  "module-apex/src/apex-contract.ts"
  "module-apex/src/synthetic-world-model.ts"
)

OUTPUT=""
FOUND=0
MISSING_LIST=()

for f in "${FILES[@]}"; do
  if [[ -f "$f" ]]; then
    OUTPUT+=$'\n\n# ============================================================\n'
    OUTPUT+="# FILE: $f"
    OUTPUT+=$'\n# ============================================================\n\n'
    OUTPUT+="$(cat "$f")"
    FOUND=$((FOUND+1))
  else
    MISSING_LIST+=("$f")
  fi
done

echo "$OUTPUT" | pbcopy

MISSING=${#MISSING_LIST[@]}
echo "Session 40 gather complete: $FOUND of ${#FILES[@]} files found, $MISSING missing."
if [[ $MISSING -gt 0 ]]; then
  echo "Missing files — check these paths before proceeding:"
  for m in "${MISSING_LIST[@]}"; do
    echo "  - $m"
  done
fi
echo "Context copied to clipboard."
