/**
 * SOVEREIGN Platform — module-cpmi
 * ReasoningChainPanel.tsx — the six-step reasoning chain surface (spec §3).
 *
 * Pick a program, run the chain (one createSovereignClient() via useReasoningChain), and
 * review the schema-validated ReasoningChainOutput with serving-tier disclosure. This is
 * where AI runs in CPMI, so it carries the CPMI-VRS Gate 1 AI disclosure. The hook owns
 * the LLM call and Logger emission.
 *
 * Version: 1.0 · Session 11 · June 23, 2026
 */

import { useMemo, useState, type CSSProperties } from "react";

import type { SovereignShellContext } from "../../sovereign-shell/shell-contract";
import { useReasoningChain } from "./useReasoningChain";
import { createDevWorldModelPort } from "./world-model-port";

export interface ReasoningChainPanelProps {
  ctx: SovereignShellContext;
}

const TIER_NOTE: Record<"live" | "cache" | "static", string> = {
  live: "Live reasoning from cpmi.reasoning-chain.",
  cache: "Served from cache — the live chain was unavailable, so the last good output for this program was reused.",
  static: "Static fallback — the reasoning service is unavailable. Output assembled from the world model; do not treat as a recommendation.",
};

export function ReasoningChainPanel({ ctx }: ReasoningChainPanelProps): JSX.Element {
  const port = useMemo(() => createDevWorldModelPort(), []);
  const programs = useMemo(() => port.listPrograms(), [port]);
  const [programId, setProgramId] = useState(programs[0] ?? "");
  const chain = useReasoningChain(ctx, { port });

  const out = chain.outcome?.output;
  const running = chain.status === "running";

  return (
    <section aria-label="Reasoning Chain" style={wrapStyle}>
      <div style={disclosureStyle}>
        <strong>CPMI-VRS Gate 1 — AI disclosure.</strong> The six-step reasoning chain is AI-generated by
        cpmi.reasoning-chain. Its output is advisory until Gate 3 human attestation; a schema-invalid output is
        never surfaced downstream. CPMI runs under enhanced monitoring (0.7× anomaly threshold).
      </div>

      <div style={rowStyle}>
        <label style={labelStyle} htmlFor="cpmi-program">Program</label>
        <select id="cpmi-program" style={selectStyle} value={programId} onChange={(e) => setProgramId(e.target.value)} disabled={running}>
          {programs.map((p) => (
            <option key={p} value={p}>{p}</option>
          ))}
        </select>
        <button style={running ? buttonDisabledStyle : buttonPrimaryStyle} disabled={running} onClick={() => void chain.runChain(programId)}>
          {running ? "Running chain…" : "Run reasoning chain"}
        </button>
      </div>

      {chain.error ? <p role="alert" style={errorStyle}>{chain.error}</p> : null}

      {out && chain.outcome ? (
        <article style={outputStyle} aria-label="Reasoning Output">
          <div style={tierBadgeStyle(chain.outcome.tier)}>{chain.outcome.tier.toUpperCase()}</div>
          <p style={tierNoteStyle}>{TIER_NOTE[chain.outcome.tier]}</p>

          <Section title={`Context (confidence: ${out.context_confidence})`}>{out.context_summary}</Section>

          <Section title={`Risk register (${out.risk_register.length})`}>
            <ul style={listStyle}>
              {out.risk_register.map((r, i) => (
                <li key={i}><strong>{r.severity}</strong> · {r.type} — {r.risk}</li>
              ))}
            </ul>
          </Section>

          <Section title={`Constraints (${out.constraint_map.length})`}>
            <ul style={listStyle}>
              {out.constraint_map.map((c, i) => (
                <li key={i}><strong>{c.constraint}</strong> — permit: {c.permitted}; prohibit: {c.prohibited}; approve: {c.requires_approval}</li>
              ))}
            </ul>
          </Section>

          <Section title={`Options (${out.option_set.length})`}>
            <ul style={listStyle}>
              {out.option_set.map((o, i) => (
                <li key={i}><strong>{o.option}</strong> — cost: {o.cost}; defers: {o.defers}; closes: {o.closes}</li>
              ))}
            </ul>
          </Section>

          <Section title="Recommendation">{out.recommendation}</Section>
          <Section title="Alternatives considered">
            <ul style={listStyle}>{out.alternatives_considered.map((a, i) => <li key={i}>{a}</li>)}</ul>
          </Section>

          <p style={out.schema_valid ? okStyle : errorStyle}>
            {out.schema_valid ? "✓ schema_valid — eligible for Gate 3 human attestation." : "✗ schema_valid: false — not surfaced downstream."}
          </p>
        </article>
      ) : null}
    </section>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }): JSX.Element {
  return (
    <div style={sectionStyle}>
      <h4 style={sectionTitleStyle}>{title}</h4>
      <div style={sectionBodyStyle}>{children}</div>
    </div>
  );
}

const wrapStyle: CSSProperties = { display: "flex", flexDirection: "column", gap: 12, maxWidth: 760 };
const disclosureStyle: CSSProperties = {
  padding: "10px 14px", background: "#fffbeb", border: "1px solid #fde68a", borderRadius: 8, color: "#92400e", fontSize: 12,
};
const rowStyle: CSSProperties = { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" };
const labelStyle: CSSProperties = { fontSize: 13, color: "#334155" };
const selectStyle: CSSProperties = { padding: "6px 10px", borderRadius: 8, border: "1px solid #cbd5e1", fontSize: 13 };
const buttonPrimaryStyle: CSSProperties = {
  padding: "8px 16px", borderRadius: 8, border: "1px solid #0c4a6e", background: "#0c4a6e", color: "#fff", cursor: "pointer", fontSize: 13, fontWeight: 600,
};
const buttonDisabledStyle: CSSProperties = { ...buttonPrimaryStyle, opacity: 0.5, cursor: "not-allowed" };
const outputStyle: CSSProperties = { padding: 16, border: "1px solid #e2e8f0", borderRadius: 10, background: "#f8fafc", display: "flex", flexDirection: "column", gap: 8 };
const sectionStyle: CSSProperties = {};
const sectionTitleStyle: CSSProperties = { margin: "6px 0 4px", fontSize: 13, color: "#0f172a" };
const sectionBodyStyle: CSSProperties = { fontSize: 13, color: "#334155", lineHeight: 1.5 };
const listStyle: CSSProperties = { margin: 0, paddingLeft: 18 };
const tierNoteStyle: CSSProperties = { margin: "6px 0 0", fontSize: 12, color: "#475569" };
const tierBadgeStyle = (tier: "live" | "cache" | "static"): CSSProperties => ({
  display: "inline-block", padding: "2px 8px", borderRadius: 999, fontSize: 11, fontWeight: 700, alignSelf: "flex-start",
  color: tier === "live" ? "#065f46" : tier === "cache" ? "#92400e" : "#7f1d1d",
  background: tier === "live" ? "#d1fae5" : tier === "cache" ? "#fef3c7" : "#fee2e2",
});
const errorStyle: CSSProperties = { margin: 0, color: "#b91c1c", fontSize: 13 };
const okStyle: CSSProperties = { margin: 0, color: "#065f46", fontSize: 13 };

export default ReasoningChainPanel;
